TopNationalParksDatabase/Models/ErrorViewModel.cs
namespace TopNationalParksDatabase.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TopNationalParksDatabase/Models/Park.cs
namespace TopNationalParksDatabase.Models
{
    public class Park
    {
        public Park() 
        { 
        }
        public int ParkID { get ; set; }      
        public string FullName { get; set; }

        public string ParkCode { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public string Website { get; set; }
        public string PhotoURL { get; set; }
      
       public IEnumerable<Park> Parks { get; set; }
       public string CurrentSortOrder { get; set; }
        public IEnumerable<Park> ParkPhotos { get; set; }
        
        public string Title { get; set; }
        public string Description { get; set; }
        
       
       
    }
}

TopNationalParksDatabase/Models/ParkViewModel.cs
//using Org.BouncyCastle.Crypto.Tls;
using System.Collections.Generic;

namespace TopNationalParksDatabase.Models
{
    public class ParkViewModel
    {
        public Park Park { get; set; }
        public int? PreviousParkId { get; set; }
        public int? NextParkId { get; set; }

        public List<Park> Alerts { get; set; }

    }
}

TopNationalParksDatabase/Models/Review.cs
namespace TopNationalParksDatabase.Models
{
    public class Review
    {
        public int ReviewID { get; set; }
        public int ParkID { get; set; }
        public string Reviewer { get; set; }
        public int Rating { get; set; }
        public string Comments { get; set; }
        public DateTime Date { get; set; }


        public string ParkName { get; set; }

       public IEnumerable<Park> Parks { get; set; }
        public IEnumerable<Review> Reviews { get; set; }
        


    }
}

TopNationalParksDatabase/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using TopNationalParksDatabase.Models;

namespace TopNationalParksDatabase.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TopNationalParksDatabase/Controllers/ParkController.cs
using Microsoft.AspNetCore.Mvc;
using Org.BouncyCastle.Crypto.Tls;
using System.Net.Http.Headers;
using System.Text.Json;
using TopNationalParksDatabase.Models;



namespace TopNationalParksDatabase.Controllers
{
    public class ParkController : Controller
    {
        private readonly IParkRepository repo;

        public ParkController(IParkRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index()
        {       
            var parks = repo.GetAllParks();           
           
           return View (parks);
        }


        public IActionResult ViewPark(int id)
        {
            
            var park = repo.GetPark(id);
            var previousParkId = repo.GetPreviousPark(id)?.ParkID;
            var nextParkId = repo.GetNextPark(id)?.ParkID;
                    var parkViewModel = new ParkViewModel
            {
                Park = park,
                PreviousParkId = previousParkId,
                NextParkId = nextParkId
            };
            IEnumerable<Park> alerts = repo.GetAlertsByParkCode();
            IEnumerable<Park> parkAlerts = alerts.Where(a => a.ParkCode !=null && a.ParkCode == park.ParkCode);
            List<Park> parkAlertsList = parkAlerts.ToList();
            parkViewModel.Alerts = parkAlertsList;


            return View(parkViewModel);
        }
       



        public IActionResult UpdatePark(int id)
        {
           Park park = repo.GetPark(id);
            if (park == null)
            {
                return View("ParkNotFound");
            }
            return View(park);
        }

        public IActionResult UpdateParkToDatabase(Park park)
        {
            repo.UpdatePark(park);
            return RedirectToAction("ViewPark", new {id = park.ParkID});
        }

       public IActionResult InsertPark()
        {
            var park = new Park();
            return View(park);
        }

        public IActionResult InsertParkToDatabase(Park parkToInsert)
        {
            repo.InsertPark(parkToInsert);
            return RedirectToAction("Index");
        }

        public IActionResult DeletePark(Park park)
        {
            repo.DeletePark(park);
            return RedirectToAction("Index");
        }

        public IActionResult Gallery()
        {
            var photos = repo.Gallery();
            return View(photos);
        }







    }
}

TopNationalParksDatabase/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using TopNationalParksDatabase.Models;
namespace TopNationalParksDatabase.Controllers
{
    public class ReviewController : Controller
    {
        private readonly IReviewRepository repo;
        public ReviewController(IReviewRepository repo)
        {
            this.repo = repo;
        }
        public IActionResult Index(string sortBy = "rating", string sortOrder = "asc")
        {
            var reviews = repo.GetAllReviews();
            switch (sortBy)
            {
                case "rating":
                    if (sortOrder == "asc")
                        reviews = reviews.OrderBy(r => r.Rating);
                    else
                        reviews = reviews.OrderByDescending(r => r.Rating);
                    break;
                case "date":
                    if (sortOrder == "asc")
                        reviews = reviews.OrderBy(r => r.Date);
                    else
                        reviews = reviews.OrderByDescending(r => r.Date);
                    break;
                case "park name":
                    if (sortOrder == "asc")
                        reviews = reviews.OrderBy(r => r.ParkName);
                    else
                        reviews = reviews.OrderByDescending(r => r.ParkName);
                    break;
                default:
                    break;

            }
            return View(reviews);
        }

        public IActionResult AddReview()
        {
            var review = repo.AssignPark();
            return View(review);
        }

        public IActionResult AddReviewToDatabase(Review reviewToInsert)
        {
            repo.AddReview(reviewToInsert);
            return RedirectToAction("Index");
        }
       
    }
}

TopNationalParksDatabase/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
<style>
    .bg {
        background-color: #a64418;
    }
    .text-center{
        
        color:cornsilk;
        font-family:Montserrat;
       
    }

    

</style>
    

<body id="background-container"></body>
    
   


    <div class="text-center">

    <h1 class="display-4">Your National Parks</h1>
    <br />
    <h3>A U.S. National Parks Directory</h3>
   
   @* <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>*@

</div>

TopNationalParksDatabase/Views/Park/Gallery.cshtml
@model IEnumerable<Park>
<style>
    .bg {
        background-color: #a64418;
    }
</style>
<body class = "background"></body>
<h2>National Parks Photo Gallery</h2>
<br />
<div class="photo-gallery">
   @foreach(var photo in Model)
        {   
            if(!string.IsNullOrEmpty(photo.PhotoURL))
             { 
                <img src="@photo.PhotoURL" alt="@photo.FullName" title="@photo.FullName" class="gallery-photo" style="width: 300px; height: 300px;" />
              
             }
        }
    
</div>

TopNationalParksDatabase/Views/Park/Index.cshtml
@model IEnumerable<Park>



    


<h2>U.S. National Parks</h2>
<br />  
<body class="background"></body>
<div class="button-container">
    <a href="/Review/AddReview/" class="btn btn-outline-primary custom-btn">Review A Park</a>

    <a href="/Park/InsertPark/" class="btn btn-outline-primary custom-btn">Add A Park</a>
</div>
<br />


<table class="table" id ="myTable">
    <tr>
        @*<th>Park ID</th>   *@   
        <th onclick="sortTable(0)" class="sortable">Sort Parks By Name</th>
        <th>Park Code</th>
        <th>Phone Number</th>
        <th>Email Address</th>
        <th>Website</th>
    </tr>

    @foreach (var park in @Model)
    {
        <tr>
            @*<td><a href="/Park/ViewPark/@park.ParkID" class="btn btn-outline-primary custom-btn">@park.ParkID</a></td>*@
            <td><a href="/Park/ViewPark/@park.ParkID" class="btn btn-outline-primary custom-btn">@park.FullName</a></td>
            <td>@park.ParkCode</td>
            <td>@park.PhoneNumber</td>
            <td>@park.EmailAddress</td>
            <td><button type="button" onclick="window.open('@park.Website', '_blank')" class="btn btn-outline-primary custom-btn">Visit Park Website</button></td>
        </tr>
    }
</table>
<script>
    function sortTable(n) {
        var table, rows, switching,i , x, y, shouldSwitch, dir, switchcount = 0;
        table = document.getElementById("myTable");
        switching = true;
    
        dir = "asc";
    
        while (switching) {
            
           switching = false;
            rows = table.rows;
      
            for (i = 1; i < (rows.length-1); i++) {
            
                shouldSwitch = false;
               
                x = rows[i].getElementsByTagName("TD")[n];
                y = rows[i + 1].getElementsByTagName("TD")[n];
               
                if (dir == "asc") {
                    if (x.innerHTML.toLowerCase() > y.innerHTML.toLowerCase()) {
                      
                        shouldSwitch = true;
                        break;
                    }
                } else if (dir == "desc") {
                    if (x.innerHTML.toLowerCase() < y.innerHTML.toLowerCase()) {
                  
                        shouldSwitch = true;
                        break;
                    }
                }
            }
            if (shouldSwitch) {
           
                rows[i].parentNode.insertBefore(rows[i + 1],rows[i]);
                switching = true;
           
               switchcount++;
            } else {
           
                if (switchcount == 0 && dir == "asc") {
                    dir = "desc";
                    switching = true;
                }
            }
        }
    }    

    //function sortTable(n) {
    //    var table, rows, switching, i, j, shouldSwitch, dir, switchcount = 0;
    //    table = document.getElementById("myTable");
    //    switching = true;
    //    dir = "asc";

    //    while (switching) {
    //        switching = false;
    //        rows = table.rows;
    //        for (i = 1; i < rows.length-1; i++) {
    //            shouldSwitch = false;
    //            var firstRow = table.rows[1];
    //            var secondRow=table.rows[2];
    //            for (j = i+1 ; j < rows.length; j++) {
    //                var x = rows[i].getElementsByTagName("TD")[n].innerHTML.toLowerCase();
    //                var y = rows[j].getElementsByTagName("TD")[n].innerHTML.toLowerCase();
    //                if (dir == "desc") {
    //                    if (x > y) {
    //                        shouldSwitch = true;
    //                        break;
    //                    }
    //                } else if (dir == "asc") {
    //                    if (x < y) {
    //                        shouldSwitch = true;
    //                        break;
    //                    }
    //                }
    //            }
    //            if (shouldSwitch) {
    //               rows[i].parentNode.insertBefore(rows[j], rows[i]);
    //                switching = true;
    //                switchcount++;
    //            }
    //        }
    //        if (switchcount == 0 && dir == "asc") {
    //            dir = "desc";
    //            switching = true;
    //        }
    //    }
    //    table.rows[1] = firstRow;
    //    table.rows[2] = secondRow;
    //}

</script>

TopNationalParksDatabase/Views/Park/InsertPark.cshtml
@model Park
<body class="background">
</body>
<h2>Create a New Park</h2>

@using (Html.BeginForm("InsertParkToDatabase", "Park", "Post"))
{
    <input asp-for="ParkID" type="hidden" value="" />

    <label asp-for="FullName" class="control-label">Name</label>
    <input type="text" name="FullName" class="form-control" value="" />

    <label asp-for="ParkCode" class="control-label">Park Code</label>
    <input type="text" step="0.01" name="ParkCode" class="form-control" value="" />

    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
    <input type="text" step="0.01" name="PhoneNumber" class="form-control" value="" /> 

    <label asp-for="EmailAddress" class="control-label">Email Address</label>
    <input type="text" step="0.01" name="EmailAddress" class="form-control" value="" />

    <label asp-for="Website" class="control-label">Website</label>
    <input type="text" step="0.01" name="Website" class="form-control" value="" />

    <br />

    <input type="submit" value="Add A Park" class="btn btn-outline-primary custom-btn" />
}

TopNationalParksDatabase/Views/Park/UpdatePark.cshtml
@model Park
<body class="background">
</body>
<h2>Update @Model.FullName</h2>

@using (Html.BeginForm("UpdateParkToDatabase", "Park", "Post"))
{
    <input asp-for="ParkID" type="hidden" value="@Model.ParkID" />

    <label asp-for="FullName" class="control-label">Name</label>
    <input type="text" name="FullName" class="form-control" value="@Model.FullName" />

    <label asp-for="ParkCode" class="control-label">Park Code</label>
    <input type="text" step="0.01" name="ParkCode" class="form-control" value="@Model.ParkCode" />

    <label asp-for="PhoneNumber" class="control-label">Phone Number</label>
    <input type="text" step="0.01" name="PhoneNumber" class="form-control" value="@Model.PhoneNumber" />

    <label asp-for="EmailAddress" class="control-label">Email Address</label>
    <input type="text" step="0.01" name="EmailAddress" class="form-control" value="@Model.EmailAddress" />

    <label asp-for="Website" class="control-label">Website</label>
    <input type="text" step="0.01" name="Website" class="form-control" value="@Model.Website" />
    <br />  
    
    <input type="submit" value="Update Park" class="btn btn-primary custom-btn" />
    
}

TopNationalParksDatabase/Views/Park/ViewPark.cshtml
@*@model Park

<style>
    a, .nav-link {
        color: rgba(255, 255, 255, .8);
        text-decoration: none;
        
    }
</style>


<table class="table">
    <tr>
      
        <th>Name</th>
        <th>Park Code</th>
        <th>Phone Number</th>
        <th>Email Address</th>
        <th>Website</th>
    </tr>
    <tr>
       
        <td>@Model.FullName</td>
        <td>@Model.ParkCode</td>
        <td>@Model.PhoneNumber</td>
        <td>@Model.EmailAddress</td>
        <td><button type="button" onclick="window.open('@Model.Website', '_blank')" class="btn btn-outline-primary custom-btn">Visit Park Website</button></td>
    </tr>
</table>

<body class="background">
</body>


<div class="btn btn-outline-primary custom-btn">
    @Html.ActionLink("Update Park", "UpdatePark", "Park", new {id = Model.ParkID})
</div>

<br />
<br />

<div style="display: block">

    @using (Html.BeginForm("DeletePark", "Park", "Post"))
    {
        <input type="hidden" asp-for="ParkID" value="@Model.ParkID" />
        <input type="submit" onclick="return confirm('Are you sure?')" class="btn btn-outline-danger" value="Delete Park" />
    }
</div>




<div class="park-details">
    <h2>@Model.FullName</h2>
    <img src="@Model.PhotoURL" alt="@Model.FullName" class="park-photo" />
</div>
*@

@model ParkViewModel

<style>
    a, .nav-link {
        color: rgba(255, 255, 255, .8);
        text-decoration: none;
    }
</style>

<table class="table">
    <tr>
        <th>Name</th>
        <th>Park Code</th>
        <th>Phone Number</th>
        <th>Email Address</th>
        <th>Website</th>
    </tr>
    <tr>
        <td>@Model.Park.FullName</td>
        <td>@Model.Park.ParkCode</td>
        <td>@Model.Park.PhoneNumber</td>
        <td>@Model.Park.EmailAddress</td>
        <td><button type="button" onclick="window.open('@Model.Park.Website', '_blank')" class="btn btn-outline-primary custom-btn">Visit Park Website</button></td>
    </tr>
</table>

<body class="background">
</body>

<div class="btn btn-outline-primary custom-btn">
    @Html.ActionLink("Update Park", "UpdatePark", "Park", new { id = Model.Park.ParkID })
</div>

<br />
<br />

<div style="display: block">
    @using (Html.BeginForm("DeletePark", "Park", "Post"))
    {
        <input type="hidden" asp-for="Park.ParkID" value="@Model.Park.ParkID" />
        <input type="submit" onclick="return confirm('Are you sure?')" class="btn btn-outline-danger" value="Delete Park" />
    }
</div>
<br />  



@if (Model.PreviousParkId != null || Model.NextParkId != null)
{
    <div class="button-container-pre-next">
        @if (Model.PreviousParkId != null)
        {
            <a href="@Url.Action("ViewPark", new { id = Model.PreviousParkId })" class="btn btn-outline-primary custom-btn"><i class="fas fa-chevron-left"></i>Previous</a>
        }

        @if (Model.NextParkId != null)
        {
            <a href="@Url.Action("ViewPark", new { id = Model.NextParkId })" class="btn btn-outline-primary custom-btn">Next<i class="fas fa-chevron-right"></i></a>
        }
    </div>
}
<br />
<br />
<h2>Alerts:</h2>
<div class = "alert">
@if (Model.Alerts.Any())
{
    <ul>
        @foreach (var alert in Model.Alerts)
        {
            <li>@alert.Title - @alert.Description</li>
        }
    </ul>
}
else
{
    <p>No alerts available.</p>
}
</div>
<br />  
<div class="park-details">
    <h2>@Model.Park.FullName</h2>
    <img src="@Model.Park.PhotoURL" alt="@Model.Park.FullName" class="park-photo" />
</div>

TopNationalParksDatabase/Views/Review/AddReview.cshtml
@model Review
<body class="background">
</body>

<h2>Review A Park</h2>

@using(Html.BeginForm("AddReviewToDatabase", "Review", "Post"))
{
    <div class="form-group">
       <label for="">Select A Park</label>
       <select class="form-control" name="ParkID" value="">
            @foreach (var park in Model.Parks)
            {
                <option value ="@park.ParkID">@park.FullName</option>
            }
        </select>

    </div>

    <input asp-for="ReviewID" type ="hidden" value =""/>

    <label asp-for="Reviewer" class="control-label">Name</label>
    <input type="text" name ="Reviewer" class="form-control" value=""/>
    <br />
    <div>
    <label asp-for="Rating" class="control-label">Rate From 0-5 Hikers</label>
    <span class="rating">
    <input type="number" step="1" min="0" max="5" name="Rating" class="form-control"/>
    <i class="fas fa-hiking"></i>
    </span>
    </div>
   <br />

    <label asp-for="Comments" class="control-label">Leave Feedback For This Park</label>
    <input type="text"  name="Comments" class="form-control"/>

    <label asp-for="Date" class="control-label">Enter Today's Date</label>
    <input type="date"  name="Date" class="form-control"/>
    <br />
    <input type ="submit" value="Create Review" class="btn btn-outline-primary custom-btn"/>
}

TopNationalParksDatabase/Views/Review/Index.cshtml
@*@functions {
    public static string RenderHikers(int rating)
    {
        string stars = string.Empty;
        for (int i = 1; i <= 5; i++)
        {
            if (i <= rating)
            {
                stars += "<i class='fas fa-hiking'></i>";
            }
            else
            {
                stars += "<i class='far fa-hiking'></i>";
            }
        }
        return stars;
    }
}*@

@model IEnumerable<Review>


<body class="background">
</body>
<h2>National Park Reviews</h2>
<br />  
<div style="display:block">
    <a href="/Review/AddReview/" class="btn btn-outline-primary custom-btn ">Review A Park</a>
</div>

<div class="sorting">
    <form action="/Review/Index" method="get">
        <label for="sort">Sort By:</label>
        <select id="sort" name="sortBy">
            <option value="rating">Rating</option>
            <option value="date">Date</option>
            <option value="park name">Park Name</option>
        </select>

        <label for="sortOrder">Sort Order:</label>
        <select id="sortOrder" name="sortOrder">
            <option value="asc">Ascending</option>
            <option value="desc">Descending</option>
        </select>

        <button type="submit">Sort</button>
    </form>
</div>


<table class="table">
    <tr>
        @*<th>Review ID</th>
        <th>Park ID</th>*@
        <th>Park Name</th>
        <th>Name</th>
        <th>Rating</th>
        <th>Comments</th>
        <th>Date</th>
    </tr>
    @foreach (var review in @Model)
    {
       <tr>
        @*<td>@review.ReviewID</td>
        <td>@review.ParkID</td>*@
        <td>@review.ParkName</td>
        <td>@review.Reviewer</td>
            <td>
                @for (int i = 1; i <= 5; i++)
                {
                    <i class="@(i <= review.Rating ? "hiker" : "gray-hiker") fas fa-hiking"></i>
                }
            </td>

        <td>@review.Comments</td>
        <td>@review.Date.ToString("MM-dd-yyyy")</td>
       </tr>

    }
</table>

TopNationalParksDatabase/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] National Parks Directory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TopNationalParksDatabase.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link rel="stylesheet" href="~/lib/jquery/dist/jquery.js" />
  <style>
      .bg {
            background-color: #a64418;
            
      }
     
         
  </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">National Parks Directory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Park" asp-action="Index">Parks</a>
                        </li>
                        <li class=" nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Review" asp-action="Index">Reviews</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Park" asp-action="Gallery">Photo Gallery</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - TopNationalParksDatabase - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>